---
- hosts: all
  become: true
  vars:
    disks: [ '/dev/sdc' ]    
  tasks:
  - name: install xfs
    package:
      name: xfsprogs
      state: latest
  - name: "parted"
    shell: |
      if
          [ -b {{ item }} ]
      then
          parted --script "{{ item }}" mklabel gpt mkpart primary 1MiB 100%
      fi
    args:
      creates: '{{ item }}1'
      executable: '/bin/bash'
    with_items: '{{ disks }}'

  - name: Create filesystem on the first partition
    filesystem:
      dev: '{{ item }}1'
      force: yes
      fstype: xfs
    with_items: '{{ disks }}'

  - name: "mnt"
    file:
      path: /data/db
      owner: mongodb
      group: mongodb
      state: directory

  - name: Get UUID for partition
    command: blkid -s UUID -o value "{{ item }}1"
    register: disk_blkid
    with_items: '{{ disks }}'
    changed_when: False

  - name: "Mount additional disk"
    mount:
      name: /data
      fstype: xfs
      opts: defaults
      passno: '0'
      src: 'UUID={{ item.1.stdout }}'
      state: '{{ item.0.mount_state|d("mounted") }}'
    with_together:
      - '{{ disks }}'
      - '{{ disk_blkid.results }}'

