---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - debug: var=ansible_distribution
    - debug: var=ansible_service_mgr
    - include: tasks/install-on-ubuntu.yml
      vars: 
        install_pkg: mongodb-org-shell 
      when: ansible_distribution == "Ubuntu"



