---
- hosts: all
  become: yes
  vars_files: 
    - vars/global.yml
  tasks:
    - debug: var=ansible_distribution
    - debug: var=ansible_service_mgr
    - debug: var=ansible_os_family
    - debug: var=mongo_user

    - include: tasks/install-on-ubuntu.yml
      when: ansible_os_family == "Debian"

    - include: tasks/install-on-rh.yml
      when: ansible_os_family != "Debian"

    - name:  ensure service is stopped
      service:
        name: mongod
        state: stopped

    - include: tasks/reset-data-dir.yml
    - include: tasks/update-config.yml

    - name:  start
      service:
        name: mongod
        state: started

- hosts: boot-strap-server
  become: yes
  vars_files: 
    - vars/global.yml
  tasks:
    - include: tasks/init-replica-set.yml

