---
- hosts: all
  become: yes
  vars_files: 
    - vars/global.yml
  tasks:
    - debug: var=ansible_distribution
    - debug: var=ansible_service_mgr
    - debug: ansible_os_family
    - debug: var=mongo_user

    - include: tasks/install-on-ubuntu.yml
      when: ansible_os_family == "Debian"

    - include: tasks/install-on-rh.yml
      when: ansible_os_family != "Debian"

    - name: create mongo data folder
      file:
        path: /data/db
        owner: "{{mongo_user}}"
        group: "{{mongo_user}}"
        state: directory
        recurse: yes

    - name: update config 
      copy:
        src: files/mongod.conf
        dest: /etc/mongod.conf
        mode: 0755

    - name: restart mongod with new config
      service:
        name: mongod
        state: restarted

