---
- hosts: all
  become: yes
  vars_files:
    - vars/global.yml

  tasks:

    - name: stop mongod 
      service:
        name: mongod
        state: stopped

    - include: tasks/reset-data-dir.yml 
    - include: tasks/update-config.yml 

    - name: start mongod
      service:
        name: mongod
        state: started

- hosts: boot-strap-server
  become: yes
  vars_files:
    - vars/global.yml
  tasks:
    - include: tasks/init-replica-set.yml


