---
   - name: disable selinux
     selinux:
       policy: targeted
       state: permissive

   - name: Add repository
     yum_repository:
       name: mongodb-org-3.4
       description: Mongo Repo 
       baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
       gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
       gpgcheck: yes

   - include: ./common-install.yml

#   - name: install mongo packages
#     package: pkg="{{ install_pkg | default('mongodb-org') }}" state=present
#
#   - name: install tree util
#     package: pkg="tree" state=present
